function MthShoulder = find_MthShoulder(InertiaLeg,InertiaBody,ddrPB,ddthHand,ddthWaist,ddthShoulder,dthHand,dthWaist,dthShoulder,g,mBody,mLeg,rArm,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist)
%FIND_MTHSHOULDER
%    MTHSHOULDER = FIND_MTHSHOULDER(INERTIALEG,INERTIABODY,DDRPB,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHWAIST,DTHSHOULDER,G,MBODY,MLEG,RARM,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jul-2020 21:35:33

t2 = dthHand.^2;
t3 = dthWaist.^2;
t4 = rBody.^2;
t5 = rBodyMCD.^2;
t6 = rLegMCD.^2;
t7 = pi./2.0;
t8 = t7+thHand;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thShoulder;
t12 = cos(t11);
t13 = sin(t11);
t14 = t11+thWaist;
t15 = cos(t14);
t16 = sin(t14);
t17 = t12.^2;
t18 = t13.^2;
t19 = t15.^2;
t20 = t16.^2;
MthShoulder = InertiaLeg.*ddthHand+InertiaBody.*ddthHand+InertiaLeg.*ddthWaist+InertiaLeg.*ddthShoulder+InertiaBody.*ddthShoulder+ddrPB.*mBody.*rBodyMCD.*t12+ddrPB.*mLeg.*rBody.*t12+ddrPB.*mLeg.*rLegMCD.*t15+ddthHand.*mBody.*t5.*t17+ddthHand.*mBody.*t5.*t18+ddthShoulder.*mBody.*t5.*t17+ddthShoulder.*mBody.*t5.*t18+ddthHand.*mLeg.*t4.*t17+ddthHand.*mLeg.*t4.*t18+ddthHand.*mLeg.*t6.*t19+ddthHand.*mLeg.*t6.*t20+ddthWaist.*mLeg.*t6.*t19+ddthWaist.*mLeg.*t6.*t20+ddthShoulder.*mLeg.*t4.*t17+ddthShoulder.*mLeg.*t4.*t18+ddthShoulder.*mLeg.*t6.*t19+ddthShoulder.*mLeg.*t6.*t20+g.*mBody.*rBodyMCD.*t12+g.*mLeg.*rBody.*t12+g.*mLeg.*rLegMCD.*t15+mBody.*rArm.*rBodyMCD.*t2.*t9.*t13-mBody.*rArm.*rBodyMCD.*t2.*t10.*t12+mLeg.*rArm.*rBody.*t2.*t9.*t13-mLeg.*rArm.*rBody.*t2.*t10.*t12+mLeg.*rArm.*rLegMCD.*t2.*t9.*t16-mLeg.*rArm.*rLegMCD.*t2.*t10.*t15-mLeg.*rBody.*rLegMCD.*t3.*t12.*t16+mLeg.*rBody.*rLegMCD.*t3.*t13.*t15+ddthHand.*mBody.*rArm.*rBodyMCD.*t9.*t12+ddthHand.*mBody.*rArm.*rBodyMCD.*t10.*t13+ddthHand.*mLeg.*rArm.*rBody.*t9.*t12+ddthHand.*mLeg.*rArm.*rBody.*t10.*t13+ddthHand.*mLeg.*rArm.*rLegMCD.*t9.*t15+ddthHand.*mLeg.*rArm.*rLegMCD.*t10.*t16+ddthHand.*mLeg.*rBody.*rLegMCD.*t12.*t15.*2.0+ddthHand.*mLeg.*rBody.*rLegMCD.*t13.*t16.*2.0+ddthWaist.*mLeg.*rBody.*rLegMCD.*t12.*t15+ddthWaist.*mLeg.*rBody.*rLegMCD.*t13.*t16+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t12.*t15.*2.0+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t13.*t16.*2.0-dthHand.*dthWaist.*mLeg.*rBody.*rLegMCD.*t12.*t16.*2.0+dthHand.*dthWaist.*mLeg.*rBody.*rLegMCD.*t13.*t15.*2.0-dthWaist.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t12.*t16.*2.0+dthWaist.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t13.*t15.*2.0;
