function vG = find_vG(dthHand,dthWaist,dthShoulder,dxHand,dyHand,mArm,mBody,mLeg,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist)
%FIND_VG
%    VG = FIND_VG(T,DTHHAND,DTHWAIST,DTHSHOULDER,DXHAND,DYHAND,MARM,MBODY,MLEG,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:55:43

t2 = dthHand+dthShoulder;
t4 = mArm+mBody+mLeg;
t5 = -dxHand;
t6 = pi./2.0;
t3 = dthWaist+t2;
t7 = 1.0./t4;
t8 = t6+thHand;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thShoulder;
t12 = cos(t11);
t13 = sin(t11);
t14 = t11+thWaist;
t15 = dthHand.*rArm.*t9;
t16 = dthHand.*rArm.*t10;
vG = [-t7.*(-mArm.*(dxHand-dthHand.*rArmMCD.*t10)+mBody.*(t5+t16+rBodyMCD.*t2.*t13)+mLeg.*(t5+t16+rLegMCD.*t3.*sin(t14)+rBody.*t2.*t13)),t7.*(mArm.*(dyHand+dthHand.*rArmMCD.*t9)+mBody.*(dyHand+t15+rBodyMCD.*t2.*t12)+mLeg.*(dyHand+t15+rLegMCD.*t3.*cos(t14)+rBody.*t2.*t12))];
