function KE = find_KE(t,InertiaLeg,InertiaArm,InertiaLBody,InertiaUBody,dthXip,dthHand,dthWaist,dthShoulder,dxHand,dyHand,g,mArm,mLBody,mLeg,mPB,mUBody,rArm,rArmMCD,rLBody,rLBodyMCD,rLegMCD,rUBody,rUBodyMCD,thHand,thShoulder,thWaist,thXip,yHand)
%FIND_KE
%    KE = FIND_KE(T,INERTIALEG,INERTIAARM,INERTIALBODY,INERTIAUBODY,DTHXIP,DTHHAND,DTHWAIST,DTHSHOULDER,DXHAND,DYHAND,G,MARM,MLBODY,MLEG,MPB,MUBODY,RARM,RARMMCD,RLBODY,RLBODYMCD,RLEGMCD,RUBODY,RUBODYMCD,THHAND,THSHOULDER,THWAIST,THXIP,YHAND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Nov-2020 17:09:32

t2 = dthHand+dthShoulder;
t5 = -dxHand;
t6 = pi./2.0;
t3 = dthXip+t2;
t4 = dthWaist+t2;
t7 = t6+thHand;
t8 = cos(t7);
t9 = sin(t7);
t10 = t7+thShoulder;
t11 = cos(t10);
t12 = sin(t10);
t13 = t10+thWaist;
t14 = t10+thXip;
t15 = rArm.*t9;
t19 = dthHand.*rArm.*t8;
t16 = cos(t14);
t17 = sin(t13);
t18 = sin(t14);
t20 = dthHand.*t15;
t21 = rUBody.*t12;
t22 = rUBody.*t2.*t11;
t23 = t2.*t21;
KE = (InertiaLeg.*(dthWaist+t3).^2)./2.0+(InertiaArm.*dthHand.^2)./2.0+(InertiaLBody.*t3.^2)./2.0+(InertiaUBody.*t2.^2)./2.0+(mLeg.*((t5+t20+t23+rLBody.*t3.*t18+rLegMCD.*t4.*t17).^2+(dyHand+t19+t22+rLegMCD.*t4.*cos(t13)+rLBody.*t3.*t16).^2))./2.0+(mPB.*(dxHand.^2+dyHand.^2))./2.0+(mLBody.*((dyHand+t19+t22+rLBodyMCD.*t3.*t16).^2+(t5+t20+t23+rLBodyMCD.*t3.*t18).^2))./2.0+(mArm.*((dxHand-dthHand.*rArmMCD.*t9).^2+(dyHand+dthHand.*rArmMCD.*t8).^2))./2.0+(mUBody.*((dyHand+t19+rUBodyMCD.*t2.*t11).^2+(t5+t20+rUBodyMCD.*t2.*t12).^2))./2.0+g.*mLBody.*(t15+t21+yHand+rLBodyMCD.*t18)+g.*mArm.*(yHand+rArmMCD.*t9)+g.*mLeg.*(t15+t21+yHand+rLBody.*t18+rLegMCD.*t17)+g.*mPB.*yHand+g.*mUBody.*(t15+yHand+rUBodyMCD.*t12);
