function TauShoulder = find_TauShoulder(InertiaLeg,InertiaLBody,InertiaUBody,ddrPB,ddthXip,ddthHand,ddthWaist,ddthShoulder,dthXip,dthHand,dthWaist,dthShoulder,g,mLBody,mLeg,mUBody,rArm,rLBody,rLBodyMCD,rLegMCD,rUBody,rUBodyMCD,thHand,thShoulder,thWaist,thXip)
%FIND_TAUSHOULDER
%    TAUSHOULDER = FIND_TAUSHOULDER(INERTIALEG,INERTIALBODY,INERTIAUBODY,DDRPB,DDTHXIP,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHXIP,DTHHAND,DTHWAIST,DTHSHOULDER,G,MLBODY,MLEG,MUBODY,RARM,RLBODY,RLBODYMCD,RLEGMCD,RUBODY,RUBODYMCD,THHAND,THSHOULDER,THWAIST,THXIP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Nov-2020 17:13:19

t2 = dthXip.^2;
t3 = dthHand.^2;
t4 = dthWaist.^2;
t5 = rLBody.^2;
t6 = rLBodyMCD.^2;
t7 = rLegMCD.^2;
t8 = rUBody.^2;
t9 = rUBodyMCD.^2;
t10 = pi./2.0;
t11 = t10+thHand;
t12 = cos(t11);
t13 = sin(t11);
t14 = t11+thShoulder;
t15 = cos(t14);
t16 = sin(t14);
t17 = t14+thWaist;
t18 = t14+thXip;
t19 = cos(t17);
t20 = cos(t18);
t21 = sin(t17);
t22 = sin(t18);
t23 = t15.^2;
t24 = t16.^2;
t25 = t19.^2;
t26 = t20.^2;
t27 = t21.^2;
t28 = t22.^2;
TauShoulder = InertiaLeg.*ddthXip+InertiaLeg.*ddthHand+InertiaLBody.*ddthXip+InertiaLeg.*ddthWaist+InertiaLBody.*ddthHand+InertiaUBody.*ddthHand+InertiaLeg.*ddthShoulder+InertiaLBody.*ddthShoulder+InertiaUBody.*ddthShoulder+ddrPB.*mLBody.*rLBodyMCD.*t20+ddrPB.*mLeg.*rLBody.*t20+ddrPB.*mLeg.*rLegMCD.*t19+ddrPB.*mLBody.*rUBody.*t15+ddrPB.*mLeg.*rUBody.*t15+ddrPB.*mUBody.*rUBodyMCD.*t15+ddthXip.*mLBody.*t6.*t26+ddthXip.*mLBody.*t6.*t28+ddthHand.*mLBody.*t8.*t23+ddthHand.*mLBody.*t6.*t26+ddthHand.*mLBody.*t8.*t24+ddthHand.*mLBody.*t6.*t28+ddthShoulder.*mLBody.*t8.*t23+ddthShoulder.*mLBody.*t6.*t26+ddthShoulder.*mLBody.*t8.*t24+ddthShoulder.*mLBody.*t6.*t28+ddthXip.*mLeg.*t5.*t26+ddthXip.*mLeg.*t5.*t28+ddthHand.*mLeg.*t5.*t26+ddthHand.*mLeg.*t8.*t23+ddthHand.*mLeg.*t7.*t25+ddthHand.*mLeg.*t8.*t24+ddthHand.*mLeg.*t5.*t28+ddthHand.*mLeg.*t7.*t27+ddthWaist.*mLeg.*t7.*t25+ddthWaist.*mLeg.*t7.*t27+ddthShoulder.*mLeg.*t5.*t26+ddthShoulder.*mLeg.*t8.*t23+ddthShoulder.*mLeg.*t7.*t25+ddthShoulder.*mLeg.*t8.*t24+ddthShoulder.*mLeg.*t5.*t28+ddthShoulder.*mLeg.*t7.*t27+ddthHand.*mUBody.*t9.*t23+ddthHand.*mUBody.*t9.*t24+ddthShoulder.*mUBody.*t9.*t23+ddthShoulder.*mUBody.*t9.*t24+g.*mLBody.*rLBodyMCD.*t20+g.*mLeg.*rLBody.*t20+g.*mLeg.*rLegMCD.*t19+g.*mLBody.*rUBody.*t15+g.*mLeg.*rUBody.*t15+g.*mUBody.*rUBodyMCD.*t15-mLBody.*rArm.*rLBodyMCD.*t3.*t13.*t20+mLBody.*rArm.*rLBodyMCD.*t3.*t12.*t22-mLeg.*rArm.*rLBody.*t3.*t13.*t20+mLeg.*rArm.*rLBody.*t3.*t12.*t22-mLeg.*rArm.*rLegMCD.*t3.*t13.*t19+mLeg.*rArm.*rLegMCD.*t3.*t12.*t21+mLBody.*rArm.*rUBody.*t3.*t12.*t16-mLBody.*rArm.*rUBody.*t3.*t13.*t15+mLeg.*rArm.*rUBody.*t3.*t12.*t16-mLeg.*rArm.*rUBody.*t3.*t13.*t15-mLeg.*rLBody.*rLegMCD.*t2.*t19.*t22+mLeg.*rLBody.*rLegMCD.*t2.*t20.*t21+mLeg.*rLBody.*rLegMCD.*t4.*t19.*t22-mLeg.*rLBody.*rLegMCD.*t4.*t20.*t21+mUBody.*rArm.*rUBodyMCD.*t3.*t12.*t16-mUBody.*rArm.*rUBodyMCD.*t3.*t13.*t15+mLBody.*rLBodyMCD.*rUBody.*t2.*t16.*t20-mLBody.*rLBodyMCD.*rUBody.*t2.*t15.*t22+mLeg.*rLBody.*rUBody.*t2.*t16.*t20-mLeg.*rLBody.*rUBody.*t2.*t15.*t22+mLeg.*rLegMCD.*rUBody.*t4.*t16.*t19-mLeg.*rLegMCD.*rUBody.*t4.*t15.*t21+ddthHand.*mLBody.*rArm.*rLBodyMCD.*t12.*t20+ddthHand.*mLBody.*rArm.*rLBodyMCD.*t13.*t22+ddthHand.*mLeg.*rArm.*rLBody.*t12.*t20+ddthHand.*mLeg.*rArm.*rLBody.*t13.*t22+ddthHand.*mLeg.*rArm.*rLegMCD.*t12.*t19+ddthHand.*mLeg.*rArm.*rLegMCD.*t13.*t21+ddthHand.*mLBody.*rArm.*rUBody.*t12.*t15+ddthHand.*mLBody.*rArm.*rUBody.*t13.*t16+ddthHand.*mLeg.*rArm.*rUBody.*t12.*t15+ddthHand.*mLeg.*rArm.*rUBody.*t13.*t16+ddthXip.*mLeg.*rLBody.*rLegMCD.*t19.*t20+ddthXip.*mLeg.*rLBody.*rLegMCD.*t21.*t22+ddthHand.*mLeg.*rLBody.*rLegMCD.*t19.*t20.*2.0+ddthHand.*mLeg.*rLBody.*rLegMCD.*t21.*t22.*2.0+ddthWaist.*mLeg.*rLBody.*rLegMCD.*t19.*t20+ddthWaist.*mLeg.*rLBody.*rLegMCD.*t21.*t22+ddthShoulder.*mLeg.*rLBody.*rLegMCD.*t19.*t20.*2.0+ddthShoulder.*mLeg.*rLBody.*rLegMCD.*t21.*t22.*2.0+ddthHand.*mUBody.*rArm.*rUBodyMCD.*t12.*t15+ddthHand.*mUBody.*rArm.*rUBodyMCD.*t13.*t16+ddthXip.*mLBody.*rLBodyMCD.*rUBody.*t15.*t20+ddthXip.*mLBody.*rLBodyMCD.*rUBody.*t16.*t22+ddthHand.*mLBody.*rLBodyMCD.*rUBody.*t15.*t20.*2.0+ddthHand.*mLBody.*rLBodyMCD.*rUBody.*t16.*t22.*2.0+ddthShoulder.*mLBody.*rLBodyMCD.*rUBody.*t15.*t20.*2.0+ddthShoulder.*mLBody.*rLBodyMCD.*rUBody.*t16.*t22.*2.0+ddthXip.*mLeg.*rLBody.*rUBody.*t15.*t20+ddthXip.*mLeg.*rLBody.*rUBody.*t16.*t22+ddthHand.*mLeg.*rLBody.*rUBody.*t15.*t20.*2.0+ddthHand.*mLeg.*rLBody.*rUBody.*t16.*t22.*2.0+ddthShoulder.*mLeg.*rLBody.*rUBody.*t15.*t20.*2.0+ddthShoulder.*mLeg.*rLBody.*rUBody.*t16.*t22.*2.0+ddthHand.*mLeg.*rLegMCD.*rUBody.*t15.*t19.*2.0+ddthHand.*mLeg.*rLegMCD.*rUBody.*t16.*t21.*2.0+ddthWaist.*mLeg.*rLegMCD.*rUBody.*t15.*t19+ddthWaist.*mLeg.*rLegMCD.*rUBody.*t16.*t21+ddthShoulder.*mLeg.*rLegMCD.*rUBody.*t15.*t19.*2.0+ddthShoulder.*mLeg.*rLegMCD.*rUBody.*t16.*t21.*2.0-dthXip.*dthHand.*mLeg.*rLBody.*rLegMCD.*t19.*t22.*2.0+dthXip.*dthHand.*mLeg.*rLBody.*rLegMCD.*t20.*t21.*2.0+dthHand.*dthWaist.*mLeg.*rLBody.*rLegMCD.*t19.*t22.*2.0-dthHand.*dthWaist.*mLeg.*rLBody.*rLegMCD.*t20.*t21.*2.0-dthXip.*dthShoulder.*mLeg.*rLBody.*rLegMCD.*t19.*t22.*2.0+dthXip.*dthShoulder.*mLeg.*rLBody.*rLegMCD.*t20.*t21.*2.0+dthWaist.*dthShoulder.*mLeg.*rLBody.*rLegMCD.*t19.*t22.*2.0-dthWaist.*dthShoulder.*mLeg.*rLBody.*rLegMCD.*t20.*t21.*2.0+dthXip.*dthHand.*mLBody.*rLBodyMCD.*rUBody.*t16.*t20.*2.0-dthXip.*dthHand.*mLBody.*rLBodyMCD.*rUBody.*t15.*t22.*2.0+dthXip.*dthShoulder.*mLBody.*rLBodyMCD.*rUBody.*t16.*t20.*2.0-dthXip.*dthShoulder.*mLBody.*rLBodyMCD.*rUBody.*t15.*t22.*2.0+dthXip.*dthHand.*mLeg.*rLBody.*rUBody.*t16.*t20.*2.0-dthXip.*dthHand.*mLeg.*rLBody.*rUBody.*t15.*t22.*2.0+dthXip.*dthShoulder.*mLeg.*rLBody.*rUBody.*t16.*t20.*2.0-dthXip.*dthShoulder.*mLeg.*rLBody.*rUBody.*t15.*t22.*2.0+dthHand.*dthWaist.*mLeg.*rLegMCD.*rUBody.*t16.*t19.*2.0-dthHand.*dthWaist.*mLeg.*rLegMCD.*rUBody.*t15.*t21.*2.0+dthWaist.*dthShoulder.*mLeg.*rLegMCD.*rUBody.*t16.*t19.*2.0-dthWaist.*dthShoulder.*mLeg.*rLegMCD.*rUBody.*t15.*t21.*2.0;
