function dKE = find_dKE(t,InertiaLeg,InertiaArm,InertiaLBody,InertiaUBody,ddthXip,ddthHand,ddthWaist,ddthShoulder,ddxHand,ddyHand,dthXip,dthHand,dthWaist,dthShoulder,dxHand,dyHand,g,mArm,mLBody,mLeg,mPB,mUBody,rArm,rArmMCD,rLBody,rLBodyMCD,rLegMCD,rUBody,rUBodyMCD,thHand,thShoulder,thWaist,thXip)
%FIND_DKE
%    DKE = FIND_DKE(T,INERTIALEG,INERTIAARM,INERTIALBODY,INERTIAUBODY,DDTHXIP,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DDXHAND,DDYHAND,DTHXIP,DTHHAND,DTHWAIST,DTHSHOULDER,DXHAND,DYHAND,G,MARM,MLBODY,MLEG,MPB,MUBODY,RARM,RARMMCD,RLBODY,RLBODYMCD,RLEGMCD,RUBODY,RUBODYMCD,THHAND,THSHOULDER,THWAIST,THXIP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Nov-2020 17:09:35

t2 = ddthHand+ddthShoulder;
t3 = dthHand+dthShoulder;
t4 = dthHand.^2;
t9 = -ddxHand;
t10 = -dxHand;
t12 = pi./2.0;
t5 = ddthXip+t2;
t6 = ddthWaist+t2;
t7 = dthXip+t3;
t8 = dthWaist+t3;
t11 = t3.^2;
t15 = t12+thHand;
t13 = t7.^2;
t14 = t8.^2;
t16 = cos(t15);
t17 = sin(t15);
t18 = t15+thShoulder;
t19 = cos(t18);
t20 = sin(t18);
t21 = t18+thWaist;
t22 = t18+thXip;
t27 = ddthHand.*rArm.*t16;
t28 = dthHand.*rArm.*t16;
t29 = dthHand.*rArmMCD.*t16;
t30 = ddthHand.*rArm.*t17;
t31 = dthHand.*rArm.*t17;
t32 = rArm.*t4.*t16;
t33 = rArm.*t4.*t17;
t23 = cos(t21);
t24 = cos(t22);
t25 = sin(t21);
t26 = sin(t22);
t34 = dyHand+t29;
t35 = rUBody.*t2.*t19;
t36 = rUBody.*t3.*t19;
t37 = rUBodyMCD.*t3.*t19;
t38 = rUBody.*t2.*t20;
t39 = rUBody.*t3.*t20;
t40 = -t33;
t44 = rUBody.*t11.*t19;
t45 = rUBody.*t11.*t20;
t41 = rLBody.*t7.*t24;
t42 = rLBodyMCD.*t7.*t24;
t43 = rLegMCD.*t8.*t23;
t46 = -t45;
t47 = dyHand+t28+t37;
t48 = dyHand+t28+t36+t42;
t49 = dyHand+t28+t36+t41+t43;
dKE = mArm.*((dxHand-dthHand.*rArmMCD.*t17).*(t9+ddthHand.*rArmMCD.*t17+rArmMCD.*t4.*t16).*2.0-t34.*(ddyHand+ddthHand.*rArmMCD.*t16-rArmMCD.*t4.*t17).*2.0).*(-1.0./2.0)+(mPB.*(ddxHand.*dxHand.*2.0+ddyHand.*dyHand.*2.0))./2.0+(mLeg.*((t10+t31+t39+rLBody.*t7.*t26+rLegMCD.*t8.*t25).*(t9+t30+t32+t38+t44+rLBody.*t5.*t26+rLBody.*t13.*t24+rLegMCD.*t6.*t25+rLegMCD.*t14.*t23).*2.0+t49.*(ddyHand+t27+t35+t40+t46+rLBody.*t5.*t24-rLBody.*t13.*t26+rLegMCD.*t6.*t23-rLegMCD.*t14.*t25).*2.0))./2.0+(mUBody.*((t10+t31+rUBodyMCD.*t3.*t20).*(t9+t30+t32+rUBodyMCD.*t2.*t20+rUBodyMCD.*t11.*t19).*2.0+t47.*(ddyHand+t27+t40+rUBodyMCD.*t2.*t19-rUBodyMCD.*t11.*t20).*2.0))./2.0+(mLBody.*(t48.*(ddyHand+t27+t35+t40+t46+rLBodyMCD.*t5.*t24-rLBodyMCD.*t13.*t26).*2.0+(t10+t31+t39+rLBodyMCD.*t7.*t26).*(t9+t30+t32+t38+t44+rLBodyMCD.*t5.*t26+rLBodyMCD.*t13.*t24).*2.0))./2.0+InertiaLeg.*(ddthWaist+t5).*(dthWaist+t7)+InertiaArm.*ddthHand.*dthHand+InertiaLBody.*t5.*t7+InertiaUBody.*t2.*t3+dyHand.*g.*mPB+g.*mArm.*t34+g.*mLBody.*t48+g.*mLeg.*t49+g.*mUBody.*t47;
