function Fx_Hand = find_Fx_Hand(ddthXip,ddthHand,ddthWaist,ddthShoulder,dthXip,dthHand,dthWaist,dthShoulder,mArm,mLBody,mLeg,mUBody,rArm,rArmMCD,rLBody,rLBodyMCD,rLegMCD,rUBody,rUBodyMCD,thHand,thShoulder,thWaist,thXip)
%FIND_FX_HAND
%    FX_HAND = FIND_FX_HAND(DDTHXIP,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHXIP,DTHHAND,DTHWAIST,DTHSHOULDER,MARM,MLBODY,MLEG,MUBODY,RARM,RARMMCD,RLBODY,RLBODYMCD,RLEGMCD,RUBODY,RUBODYMCD,THHAND,THSHOULDER,THWAIST,THXIP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Nov-2020 17:09:51

t2 = dthXip.^2;
t3 = dthHand.^2;
t4 = dthShoulder.^2;
t5 = pi./2.0;
t6 = t5+thHand;
t7 = cos(t6);
t8 = sin(t6);
t9 = t6+thShoulder;
t10 = cos(t9);
t11 = sin(t9);
t12 = t9+thWaist;
t13 = t9+thXip;
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
Fx_Hand = -ddthHand.*mArm.*rArmMCD.*t8-ddthHand.*mLBody.*rArm.*t8-ddthHand.*mLeg.*rArm.*t8-ddthHand.*mUBody.*rArm.*t8-ddthXip.*mLBody.*rLBodyMCD.*t17-ddthHand.*mLBody.*rLBodyMCD.*t17-ddthShoulder.*mLBody.*rLBodyMCD.*t17-ddthXip.*mLeg.*rLBody.*t17-ddthHand.*mLeg.*rLBody.*t17-ddthShoulder.*mLeg.*rLBody.*t17-ddthHand.*mLeg.*rLegMCD.*t16-ddthWaist.*mLeg.*rLegMCD.*t16-ddthShoulder.*mLeg.*rLegMCD.*t16-ddthHand.*mLBody.*rUBody.*t11-ddthShoulder.*mLBody.*rUBody.*t11-ddthHand.*mLeg.*rUBody.*t11-ddthShoulder.*mLeg.*rUBody.*t11-ddthHand.*mUBody.*rUBodyMCD.*t11-ddthShoulder.*mUBody.*rUBodyMCD.*t11-mArm.*rArmMCD.*t3.*t7-mLBody.*rArm.*t3.*t7-mLeg.*rArm.*t3.*t7-mUBody.*rArm.*t3.*t7-mLBody.*rLBodyMCD.*t2.*t15-mLBody.*rLBodyMCD.*t3.*t15-mLBody.*rLBodyMCD.*t4.*t15-mLeg.*rLBody.*t2.*t15-mLeg.*rLBody.*t3.*t15-mLeg.*rLBody.*t4.*t15-mLeg.*rLegMCD.*t3.*t14-mLeg.*rLegMCD.*t4.*t14-mLBody.*rUBody.*t3.*t10-mLBody.*rUBody.*t4.*t10-mLeg.*rUBody.*t3.*t10-mLeg.*rUBody.*t4.*t10-mUBody.*rUBodyMCD.*t3.*t10-mUBody.*rUBodyMCD.*t4.*t10-dthWaist.^2.*mLeg.*rLegMCD.*t14-dthXip.*dthHand.*mLBody.*rLBodyMCD.*t15.*2.0-dthXip.*dthShoulder.*mLBody.*rLBodyMCD.*t15.*2.0-dthHand.*dthShoulder.*mLBody.*rLBodyMCD.*t15.*2.0-dthXip.*dthHand.*mLeg.*rLBody.*t15.*2.0-dthXip.*dthShoulder.*mLeg.*rLBody.*t15.*2.0-dthHand.*dthShoulder.*mLeg.*rLBody.*t15.*2.0-dthHand.*dthWaist.*mLeg.*rLegMCD.*t14.*2.0-dthHand.*dthShoulder.*mLeg.*rLegMCD.*t14.*2.0-dthWaist.*dthShoulder.*mLeg.*rLegMCD.*t14.*2.0-dthHand.*dthShoulder.*mLBody.*rUBody.*t10.*2.0-dthHand.*dthShoulder.*mLeg.*rUBody.*t10.*2.0-dthHand.*dthShoulder.*mUBody.*rUBodyMCD.*t10.*2.0;
