function pG = find_pG(t,mArm,mLBody,mLeg,mUBody,rArm,rArmMCD,rLBody,rLBodyMCD,rLegMCD,rUBody,rUBodyMCD,thHand,thShoulder,thWaist,thXip,xHand,yHand)
%FIND_PG
%    PG = FIND_PG(T,MARM,MLBODY,MLEG,MUBODY,RARM,RARMMCD,RLBODY,RLBODYMCD,RLEGMCD,RUBODY,RUBODYMCD,THHAND,THSHOULDER,THWAIST,THXIP,XHAND,YHAND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Nov-2020 17:09:30

t2 = mArm+mLBody+mLeg+mUBody;
t3 = pi./2.0;
t4 = t3+thHand;
t5 = 1.0./t2;
t6 = cos(t4);
t7 = sin(t4);
t8 = t4+thShoulder;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thWaist;
t12 = t8+thXip;
t13 = rArm.*t6;
t14 = rArm.*t7;
t15 = cos(t12);
t16 = sin(t12);
t17 = rUBody.*t9;
t18 = rUBody.*t10;
pG = [t5.*(mUBody.*(t13+xHand+rUBodyMCD.*t9)+mLeg.*(t13+t17+xHand+rLBody.*t15+rLegMCD.*cos(t11))+mLBody.*(t13+t17+xHand+rLBodyMCD.*t15)+mArm.*(xHand+rArmMCD.*t6)),t5.*(mUBody.*(t14+yHand+rUBodyMCD.*t10)+mLeg.*(t14+t18+yHand+rLBody.*t16+rLegMCD.*sin(t11))+mLBody.*(t14+t18+yHand+rLBodyMCD.*t16)+mArm.*(yHand+rArmMCD.*t7))];
