function InertiaG = find_InertiaG(InertiaLeg,InertiaArm,InertiaBody,mArm,mBody,mLeg,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thShoulder,thWaist)
%FIND_INERTIAG
%    INERTIAG = FIND_INERTIAG(INERTIALEG,INERTIAARM,INERTIABODY,MARM,MBODY,MLEG,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:55:41

t2 = cos(thShoulder);
t3 = cos(thWaist);
t4 = thShoulder+thWaist;
t5 = mArm.^2;
t6 = mBody.^2;
t7 = mLeg.^2;
t8 = rArm.^2;
t9 = rArmMCD.^2;
t10 = rBody.^2;
t11 = rBodyMCD.^2;
t12 = rLegMCD.^2;
t13 = mArm+mBody+mLeg;
t14 = cos(t4);
t15 = 1.0./t13.^2;
t16 = rArm.*rArmMCD.*t5.*2.0;
t17 = t5.*t8;
t18 = t5.*t9;
t19 = t6.*t11;
t20 = t7.*t10;
t21 = t7.*t12;
t23 = rBody.*rLegMCD.*t3.*t7.*2.0;
t22 = -t16;
InertiaG = InertiaLeg+InertiaArm+InertiaBody+mLeg.*t15.*(t17+t18+t19+t22+t5.*t10+t6.*t10+t5.*t12+t6.*t12+mArm.*mBody.*t10.*2.0+mArm.*mBody.*t12.*2.0-rBody.*rBodyMCD.*t6.*2.0-mArm.*mBody.*rBody.*rBodyMCD.*2.0+rArm.*rBody.*t2.*t5.*2.0-rArmMCD.*rBody.*t2.*t5.*2.0+rArm.*rLegMCD.*t5.*t14.*2.0-rArmMCD.*rLegMCD.*t5.*t14.*2.0+rBody.*rLegMCD.*t3.*t5.*2.0+rBody.*rLegMCD.*t3.*t6.*2.0-rBodyMCD.*rLegMCD.*t3.*t6.*2.0+mArm.*mBody.*rArm.*rBody.*t2.*2.0-mArm.*mBody.*rArm.*rBodyMCD.*t2.*2.0-mArm.*mBody.*rArmMCD.*rBody.*t2.*2.0+mArm.*mBody.*rArmMCD.*rBodyMCD.*t2.*2.0+mArm.*mBody.*rArm.*rLegMCD.*t14.*2.0-mArm.*mBody.*rArmMCD.*rLegMCD.*t14.*2.0+mArm.*mBody.*rBody.*rLegMCD.*t3.*4.0-mArm.*mBody.*rBodyMCD.*rLegMCD.*t3.*2.0)+mArm.*t15.*(t19+t20+t21+t23+t6.*t8+t6.*t9+t7.*t8+t7.*t9+mBody.*mLeg.*t8.*2.0+mBody.*mLeg.*t9.*2.0-rArm.*rArmMCD.*t6.*2.0-rArm.*rArmMCD.*t7.*2.0-mBody.*mLeg.*rArm.*rArmMCD.*4.0+mBody.*mLeg.*rBody.*rBodyMCD.*2.0+rArm.*rBody.*t2.*t7.*2.0+rArm.*rBodyMCD.*t2.*t6.*2.0-rArmMCD.*rBody.*t2.*t7.*2.0-rArmMCD.*rBodyMCD.*t2.*t6.*2.0+rArm.*rLegMCD.*t7.*t14.*2.0-rArmMCD.*rLegMCD.*t7.*t14.*2.0+mBody.*mLeg.*rArm.*rBody.*t2.*2.0+mBody.*mLeg.*rArm.*rBodyMCD.*t2.*2.0-mBody.*mLeg.*rArmMCD.*rBody.*t2.*2.0-mBody.*mLeg.*rArmMCD.*rBodyMCD.*t2.*2.0+mBody.*mLeg.*rArm.*rLegMCD.*t14.*2.0-mBody.*mLeg.*rArmMCD.*rLegMCD.*t14.*2.0+mBody.*mLeg.*rBodyMCD.*rLegMCD.*t3.*2.0)+mBody.*t15.*(t17+t18+t20+t21+t22+t23+t5.*t11+t7.*t11+mArm.*mLeg.*t11.*2.0-rBody.*rBodyMCD.*t7.*2.0-mArm.*mLeg.*rBody.*rBodyMCD.*2.0+rArm.*rBodyMCD.*t2.*t5.*2.0-rArmMCD.*rBodyMCD.*t2.*t5.*2.0-rBodyMCD.*rLegMCD.*t3.*t7.*2.0-mArm.*mLeg.*rArm.*rBody.*t2.*2.0+mArm.*mLeg.*rArm.*rBodyMCD.*t2.*2.0+mArm.*mLeg.*rArmMCD.*rBody.*t2.*2.0-mArm.*mLeg.*rArmMCD.*rBodyMCD.*t2.*2.0-mArm.*mLeg.*rArm.*rLegMCD.*t14.*2.0+mArm.*mLeg.*rArmMCD.*rLegMCD.*t14.*2.0-mArm.*mLeg.*rBodyMCD.*rLegMCD.*t3.*2.0);
