function pG = find_pG(mArm,mBody,mLeg,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist,xHand,yHand)
%FIND_PG
%    PG = FIND_PG(T,MARM,MBODY,MLEG,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST,XHAND,YHAND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:55:43

t2 = mArm+mBody+mLeg;
t3 = pi./2.0;
t4 = 1.0./t2;
t5 = t3+thHand;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+thShoulder;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thWaist;
t12 = rArm.*t6;
t13 = rArm.*t7;
pG = [t4.*(mLeg.*(t12+xHand+rBody.*t9+rLegMCD.*cos(t11))+mBody.*(t12+xHand+rBodyMCD.*t9)+mArm.*(xHand+rArmMCD.*t6)),t4.*(mLeg.*(t13+yHand+rBody.*t10+rLegMCD.*sin(t11))+mBody.*(t13+yHand+rBodyMCD.*t10)+mArm.*(yHand+rArmMCD.*t7))];
