function ddrPB = find_ddrPB_only(MrPB,ddthHand,ddthWaist,ddthShoulder,dthHand,dthWaist,dthShoulder,g,kPB,mArm,mBody,mLeg,mPB,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,rPB,thHand,thShoulder,thWaist)
%FIND_DDRPB_ONLY
%    DDRPB = FIND_DDRPB_ONLY(MRPB,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHWAIST,DTHSHOULDER,G,KPB,MARM,MBODY,MLEG,MPB,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,RPB,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:54:05

t2 = cos(thHand);
t3 = sin(thHand);
t4 = thHand+thShoulder;
t5 = dthHand.^2;
t6 = dthShoulder.^2;
t7 = cos(t4);
t8 = sin(t4);
t9 = t4+thWaist;
t10 = cos(t9);
t11 = sin(t9);
ddrPB = (MrPB-g.*mArm-g.*mBody-g.*mLeg-g.*mPB-kPB.*rPB+ddthHand.*mArm.*rArmMCD.*t3+ddthHand.*mBody.*rArm.*t3+ddthHand.*mBody.*rBodyMCD.*t8+ddthShoulder.*mBody.*rBodyMCD.*t8+ddthHand.*mLeg.*rArm.*t3+ddthHand.*mLeg.*rBody.*t8+ddthShoulder.*mLeg.*rBody.*t8+ddthHand.*mLeg.*rLegMCD.*t11+ddthWaist.*mLeg.*rLegMCD.*t11+ddthShoulder.*mLeg.*rLegMCD.*t11+mArm.*rArmMCD.*t2.*t5+mBody.*rArm.*t2.*t5+mBody.*rBodyMCD.*t5.*t7+mBody.*rBodyMCD.*t6.*t7+mLeg.*rArm.*t2.*t5+mLeg.*rBody.*t5.*t7+mLeg.*rBody.*t6.*t7+mLeg.*rLegMCD.*t5.*t10+mLeg.*rLegMCD.*t6.*t10+dthWaist.^2.*mLeg.*rLegMCD.*t10+dthHand.*dthShoulder.*mBody.*rBodyMCD.*t7.*2.0+dthHand.*dthShoulder.*mLeg.*rBody.*t7.*2.0+dthHand.*dthWaist.*mLeg.*rLegMCD.*t10.*2.0+dthHand.*dthShoulder.*mLeg.*rLegMCD.*t10.*2.0+dthWaist.*dthShoulder.*mLeg.*rLegMCD.*t10.*2.0)./(mArm+mBody+mLeg+mPB);
