function MthWaist = find_MthWaist(InertiaLeg,ddrPB,ddthHand,ddthWaist,ddthShoulder,dthHand,dthShoulder,g,mLeg,rArm,rBody,rLegMCD,thHand,thShoulder,thWaist)
%FIND_MTHWAIST
%    MTHWAIST = FIND_MTHWAIST(INERTIALEG,DDRPB,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHSHOULDER,G,MLEG,RARM,RBODY,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jul-2020 21:35:33

t2 = dthHand.^2;
t3 = dthShoulder.^2;
t4 = rLegMCD.^2;
t5 = pi./2.0;
t6 = t5+thHand;
t7 = cos(t6);
t8 = sin(t6);
t9 = t6+thShoulder;
t10 = cos(t9);
t11 = sin(t9);
t12 = t9+thWaist;
t13 = cos(t12);
t14 = sin(t12);
t15 = t13.^2;
t16 = t14.^2;
MthWaist = InertiaLeg.*ddthHand+InertiaLeg.*ddthWaist+InertiaLeg.*ddthShoulder+ddrPB.*mLeg.*rLegMCD.*t13+ddthHand.*mLeg.*t4.*t15+ddthHand.*mLeg.*t4.*t16+ddthWaist.*mLeg.*t4.*t15+ddthWaist.*mLeg.*t4.*t16+ddthShoulder.*mLeg.*t4.*t15+ddthShoulder.*mLeg.*t4.*t16+g.*mLeg.*rLegMCD.*t13+mLeg.*rArm.*rLegMCD.*t2.*t7.*t14-mLeg.*rArm.*rLegMCD.*t2.*t8.*t13+mLeg.*rBody.*rLegMCD.*t2.*t10.*t14-mLeg.*rBody.*rLegMCD.*t2.*t11.*t13+mLeg.*rBody.*rLegMCD.*t3.*t10.*t14-mLeg.*rBody.*rLegMCD.*t3.*t11.*t13+ddthHand.*mLeg.*rArm.*rLegMCD.*t7.*t13+ddthHand.*mLeg.*rArm.*rLegMCD.*t8.*t14+ddthHand.*mLeg.*rBody.*rLegMCD.*t10.*t13+ddthHand.*mLeg.*rBody.*rLegMCD.*t11.*t14+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t10.*t13+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t11.*t14+dthHand.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t10.*t14.*2.0-dthHand.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t11.*t13.*2.0;
