function DispObjectiveValueData(ObjectiveValueData, count)
%DISPOBJECTIVEVALUEDATA この関数の概要をここに記述
%   詳細説明をここに記述
formatOut = 'dd/HH:MM:ss';
dateString = datestr(now,formatOut);

Extra_Str = "";
for ii = 2:size(ObjectiveValueData, 1)
    Extra_Str = strcat(Extra_Str, ",(", num2str(ObjectiveValueData(ii,1), '%10.5f'), ")");
end

fprintf(strcat("目的関数 : ", num2str(ObjectiveValueData(1,1), '%10.5f'),...
    Extra_Str, ...
    "    時刻    ", dateString,...
    "    count = ", num2str(count),...
    '\n'))
fprintf(strcat('[spinValue, RateSwitchValue, Work_thValue, dthSwitchNum, thWaist_AtBodyUpStraight_Value] = \n[',...
    num2str(ObjectiveValueData(1,2), '%10.5f'), ", ",...
    num2str(ObjectiveValueData(1,3), '%10.5f'), ", ",...
    num2str(ObjectiveValueData(1,4), '%10.5f'), ", ",...
    num2str(ObjectiveValueData(1,5), '%10.5f'), ", ",...
    num2str(ObjectiveValueData(1,6), '%10.5f'), ']\n'))

% if size(ObjectiveValueData, 1) == 1
% fprintf(strcat("目的関数 : ", num2str(ObjectiveValueData(1,1), '%10.5f'),...
%     "    時刻    ", dateString,...
%     "    count = ", num2str(count),...
%     '\n'))
% fprintf(strcat('[spinValue, dthSwitchValue, MthValue] = [',...
%     num2str(ObjectiveValueData(1,2), '%10.5f'), ", ",...
%     num2str(ObjectiveValueData(1,3), '%10.5f'), ", ",...
%     num2str(ObjectiveValueData(1,4), '%10.5f'), ']\n'))
% else
%     Extra_Str = "";
%     for ii = 2:size(ObjectiveValueData, 1)
%         Extra_Str = strcat(Extra_Str, ",(", num2str(ObjectiveValueData(ii,1), '%10.5f'), ")");
%     end
%     
% fprintf(strcat("目的関数 : ", num2str(ObjectiveValueData(1,1), '%10.5f'),...
%     Extra_Str, ...
%     "    時刻    ", dateString,...
%     "    count = ", num2str(count),...
%     '\n'))
% fprintf(strcat('[spinValue, dthSwitchValue, MthValue] = [',...
%     num2str(ObjectiveValueData(1,2), '%10.5f'), ", ",...
%     num2str(ObjectiveValueData(1,3), '%10.5f'), ", ",...
%     num2str(ObjectiveValueData(1,4), '%10.5f'), ']\n'))
% end
end

