function Fx_Hand = find_Fx_Hand(ddthHand,ddthWaist,ddthShoulder,dthHand,dthWaist,dthShoulder,mArm,mBody,mLeg,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist)
%FIND_FX_HAND
%    FX_HAND = FIND_FX_HAND(DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHWAIST,DTHSHOULDER,MARM,MBODY,MLEG,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jul-2020 21:35:50

t2 = dthHand.^2;
t3 = dthShoulder.^2;
t4 = pi./2.0;
t5 = t4+thHand;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+thShoulder;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thWaist;
t12 = cos(t11);
t13 = sin(t11);
Fx_Hand = -ddthHand.*mArm.*rArmMCD.*t7-ddthHand.*mBody.*rArm.*t7-ddthHand.*mBody.*rBodyMCD.*t10-ddthShoulder.*mBody.*rBodyMCD.*t10-ddthHand.*mLeg.*rArm.*t7-ddthHand.*mLeg.*rBody.*t10-ddthShoulder.*mLeg.*rBody.*t10-ddthHand.*mLeg.*rLegMCD.*t13-ddthWaist.*mLeg.*rLegMCD.*t13-ddthShoulder.*mLeg.*rLegMCD.*t13-mArm.*rArmMCD.*t2.*t6-mBody.*rArm.*t2.*t6-mBody.*rBodyMCD.*t2.*t9-mBody.*rBodyMCD.*t3.*t9-mLeg.*rArm.*t2.*t6-mLeg.*rBody.*t2.*t9-mLeg.*rBody.*t3.*t9-mLeg.*rLegMCD.*t2.*t12-mLeg.*rLegMCD.*t3.*t12-dthWaist.^2.*mLeg.*rLegMCD.*t12-dthHand.*dthShoulder.*mBody.*rBodyMCD.*t9.*2.0-dthHand.*dthShoulder.*mLeg.*rBody.*t9.*2.0-dthHand.*dthWaist.*mLeg.*rLegMCD.*t12.*2.0-dthHand.*dthShoulder.*mLeg.*rLegMCD.*t12.*2.0-dthWaist.*dthShoulder.*mLeg.*rLegMCD.*t12.*2.0;
