function Fy_Hand = find_Fy_Hand(ddrPB,ddthHand,ddthWaist,ddthShoulder,dthHand,dthWaist,dthShoulder,g,mArm,mBody,mLeg,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist)
%FIND_FY_HAND
%    FY_HAND = FIND_FY_HAND(DDRPB,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHWAIST,DTHSHOULDER,G,MARM,MBODY,MLEG,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jul-2020 21:35:51

t2 = dthHand.^2;
t3 = dthShoulder.^2;
t4 = pi./2.0;
t5 = t4+thHand;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+thShoulder;
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+thWaist;
t12 = cos(t11);
t13 = sin(t11);
Fy_Hand = ddrPB.*mArm+ddrPB.*mBody+ddrPB.*mLeg+g.*mArm+g.*mBody+g.*mLeg+ddthHand.*mArm.*rArmMCD.*t6+ddthHand.*mBody.*rArm.*t6+ddthHand.*mBody.*rBodyMCD.*t9+ddthShoulder.*mBody.*rBodyMCD.*t9+ddthHand.*mLeg.*rArm.*t6+ddthHand.*mLeg.*rBody.*t9+ddthShoulder.*mLeg.*rBody.*t9+ddthHand.*mLeg.*rLegMCD.*t12+ddthWaist.*mLeg.*rLegMCD.*t12+ddthShoulder.*mLeg.*rLegMCD.*t12-mArm.*rArmMCD.*t2.*t7-mBody.*rArm.*t2.*t7-mBody.*rBodyMCD.*t2.*t10-mBody.*rBodyMCD.*t3.*t10-mLeg.*rArm.*t2.*t7-mLeg.*rBody.*t2.*t10-mLeg.*rBody.*t3.*t10-mLeg.*rLegMCD.*t2.*t13-mLeg.*rLegMCD.*t3.*t13-dthWaist.^2.*mLeg.*rLegMCD.*t13-dthHand.*dthShoulder.*mBody.*rBodyMCD.*t10.*2.0-dthHand.*dthShoulder.*mLeg.*rBody.*t10.*2.0-dthHand.*dthWaist.*mLeg.*rLegMCD.*t13.*2.0-dthHand.*dthShoulder.*mLeg.*rLegMCD.*t13.*2.0-dthWaist.*dthShoulder.*mLeg.*rLegMCD.*t13.*2.0;
