function dKE = find_dKE(InertiaLeg,InertiaArm,InertiaBody,ddthHand,ddthWaist,ddthShoulder,ddxHand,ddyHand,dthHand,dthWaist,dthShoulder,dxHand,dyHand,g,kPB,mArm,mBody,mLeg,mPB,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist,yHand)
%FIND_DKE
%    DKE = FIND_DKE(INERTIALEG,INERTIAARM,INERTIABODY,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DDXHAND,DDYHAND,DTHHAND,DTHWAIST,DTHSHOULDER,DXHAND,DYHAND,G,KPB,MARM,MBODY,MLEG,MPB,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST,YHAND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Nov-2020 16:23:51

t2 = ddthHand+ddthShoulder;
t3 = dthHand+dthShoulder;
t4 = dthHand.^2;
t7 = -ddxHand;
t8 = -dxHand;
t10 = pi./2.0;
t5 = ddthWaist+t2;
t6 = dthWaist+t3;
t9 = t3.^2;
t12 = t10+thHand;
t11 = t6.^2;
t13 = cos(t12);
t14 = sin(t12);
t15 = t12+thShoulder;
t16 = cos(t15);
t17 = sin(t15);
t18 = t15+thWaist;
t21 = ddthHand.*rArm.*t13;
t22 = dthHand.*rArm.*t13;
t23 = dthHand.*rArmMCD.*t13;
t24 = ddthHand.*rArm.*t14;
t25 = dthHand.*rArm.*t14;
t26 = rArm.*t4.*t13;
t27 = rArm.*t4.*t14;
t19 = cos(t18);
t20 = sin(t18);
t28 = dyHand+t23;
t29 = rBody.*t3.*t16;
t30 = rBodyMCD.*t3.*t16;
t31 = -t27;
t32 = rLegMCD.*t6.*t19;
t33 = dyHand+t22+t30;
t34 = dyHand+t22+t29+t32;
dKE = mArm.*((dxHand-dthHand.*rArmMCD.*t14).*(t7+ddthHand.*rArmMCD.*t14+rArmMCD.*t4.*t13).*2.0-t28.*(ddyHand+ddthHand.*rArmMCD.*t13-rArmMCD.*t4.*t14).*2.0).*(-1.0./2.0)+(mLeg.*(t34.*(ddyHand+t21+t31+rBody.*t2.*t16-rBody.*t9.*t17+rLegMCD.*t5.*t19-rLegMCD.*t11.*t20).*2.0+(t8+t25+rBody.*t3.*t17+rLegMCD.*t6.*t20).*(t7+t24+t26+rBody.*t2.*t17+rBody.*t9.*t16+rLegMCD.*t5.*t20+rLegMCD.*t11.*t19).*2.0))./2.0+(mPB.*(ddxHand.*dxHand.*2.0+ddyHand.*dyHand.*2.0))./2.0+(mBody.*((t8+t25+rBodyMCD.*t3.*t17).*(t7+t24+t26+rBodyMCD.*t2.*t17+rBodyMCD.*t9.*t16).*2.0+t33.*(ddyHand+t21+t31+rBodyMCD.*t2.*t16-rBodyMCD.*t9.*t17).*2.0))./2.0+InertiaArm.*ddthHand.*dthHand+InertiaLeg.*t5.*t6+InertiaBody.*t2.*t3+dyHand.*g.*mPB+g.*mArm.*t28+g.*mBody.*t33+g.*mLeg.*t34+dyHand.*kPB.*yHand.*2.0;
