function [ddth1,ddth2,ddx1,ddy1] = find_ddth1_ddth2_ddx1_ddy1(Lc1,Lc2,M1,M2,dth1,dth2,mTop,tau2,th1,th2)
%FIND_DDTH1_DDTH2_DDX1_DDY1
%    [DDTH1,DDTH2,DDX1,DDY1] = FIND_DDTH1_DDTH2_DDX1_DDY1(LC1,LC2,M1,M2,DTH1,DTH2,MTOP,TAU2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:02:19

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = M2.*mTop;
t7 = Lc2.^2;
t8 = M1.^2;
t9 = M2.^2;
t10 = dth1.^2;
t11 = dth2.^2;
t12 = th1.*2.0;
t13 = th2.*2.0;
t14 = M1.*mTop.*2.0;
t15 = 1.0./Lc2;
t16 = -th2;
t18 = M1.*M2.*2.0;
t17 = -t13;
t19 = t8.*2.0;
t20 = t16+th1;
t23 = t12+t16;
t21 = cos(t20);
t22 = sin(t20);
t24 = t12+t17;
t25 = cos(t23);
t27 = sin(t23);
t26 = cos(t24);
t28 = sin(t24);
t29 = t6.*t26;
t30 = -t29;
t31 = t6+t14+t18+t19+t30;
t32 = 1.0./t31;
ddth1 = (t15.*t32.*(M1.*t21.*tau2+M2.*t21.*tau2+mTop.*t21.*tau2+t6.*t7.*t11.*t22+(Lc1.*Lc2.*t6.*t10.*t28)./2.0+M1.*M2.*t7.*t11.*t22).*-2.0)./Lc1;
if nargout > 1
    ddth2 = (t32.*(t6.*tau2+t8.*tau2+t9.*tau2+t18.*tau2+M1.*mTop.*tau2+(M2.*t6.*t7.*t11.*t28)./2.0+Lc1.*Lc2.*M1.*t6.*t10.*t22+Lc1.*Lc2.*M2.*t6.*t10.*t22).*2.0)./(M2.*t7);
end
if nargout > 2
    ddx1 = t15.*t32.*(-M1.*t3.*tau2-M2.*t3.*tau2+M1.*t25.*tau2+M2.*t25.*tau2+Lc1.*Lc2.*t4.*t10.*t18+Lc1.*Lc2.*t4.*t10.*t19+M1.*M2.*t5.*t7.*t11+M1.*M2.*t7.*t11.*t27);
end
if nargout > 3
    ddy1 = -t15.*t32.*(M1.*t5.*tau2+M2.*t5.*tau2-M1.*t27.*tau2-M2.*t27.*tau2+Lc1.*Lc2.*t2.*t10.*t18+Lc1.*Lc2.*t2.*t10.*t19+M1.*M2.*t3.*t7.*t11+M1.*M2.*t7.*t11.*t25);
end
