function MthShoulder = find_MthShoulder(InertiaLeg,InertiaBody,ddrPB,ddthHand,ddthWaist,ddthShoulder,dthHand,dthWaist,dthShoulder,g,mBody,mLeg,rArm,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist)
%FIND_MTHSHOULDER
%    MTHSHOULDER = FIND_MTHSHOULDER(INERTIALEG,INERTIABODY,DDRPB,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DTHHAND,DTHWAIST,DTHSHOULDER,G,MBODY,MLEG,RARM,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:54:03

t2 = cos(thHand);
t3 = sin(thHand);
t4 = thHand+thShoulder;
t5 = dthHand.^2;
t6 = dthWaist.^2;
t7 = rBody.^2;
t8 = rBodyMCD.^2;
t9 = rLegMCD.^2;
t15 = pi./2.0;
t10 = cos(t4);
t11 = sin(t4);
t12 = t4+thWaist;
t20 = t4+t15;
t13 = cos(t12);
t14 = sin(t12);
t16 = t10.^2;
t17 = t11.^2;
t21 = cos(t20);
t18 = t13.^2;
t19 = t14.^2;
MthShoulder = InertiaLeg.*ddthHand+InertiaBody.*ddthHand+InertiaLeg.*ddthWaist+InertiaLeg.*ddthShoulder+InertiaBody.*ddthShoulder-ddrPB.*mBody.*rBodyMCD.*t11-ddrPB.*mLeg.*rBody.*t11-ddrPB.*mLeg.*rLegMCD.*t14+ddthHand.*mBody.*t8.*t16+ddthHand.*mBody.*t8.*t17+ddthShoulder.*mBody.*t8.*t16+ddthShoulder.*mBody.*t8.*t17+ddthHand.*mLeg.*t7.*t16+ddthHand.*mLeg.*t7.*t17+ddthHand.*mLeg.*t9.*t18+ddthHand.*mLeg.*t9.*t19+ddthWaist.*mLeg.*t9.*t18+ddthWaist.*mLeg.*t9.*t19+ddthShoulder.*mLeg.*t7.*t16+ddthShoulder.*mLeg.*t7.*t17+ddthShoulder.*mLeg.*t9.*t18+ddthShoulder.*mLeg.*t9.*t19+g.*mBody.*rBodyMCD.*t21+g.*mLeg.*rBody.*t21+g.*mLeg.*rLegMCD.*cos(t12+t15)+mBody.*rArm.*rBodyMCD.*t2.*t5.*t11-mBody.*rArm.*rBodyMCD.*t3.*t5.*t10+mLeg.*rArm.*rBody.*t2.*t5.*t11-mLeg.*rArm.*rBody.*t3.*t5.*t10+mLeg.*rArm.*rLegMCD.*t2.*t5.*t14-mLeg.*rArm.*rLegMCD.*t3.*t5.*t13-mLeg.*rBody.*rLegMCD.*t6.*t10.*t14+mLeg.*rBody.*rLegMCD.*t6.*t11.*t13+ddthHand.*mBody.*rArm.*rBodyMCD.*t2.*t10+ddthHand.*mBody.*rArm.*rBodyMCD.*t3.*t11+ddthHand.*mLeg.*rArm.*rBody.*t2.*t10+ddthHand.*mLeg.*rArm.*rBody.*t3.*t11+ddthHand.*mLeg.*rArm.*rLegMCD.*t2.*t13+ddthHand.*mLeg.*rArm.*rLegMCD.*t3.*t14+ddthHand.*mLeg.*rBody.*rLegMCD.*t10.*t13.*2.0+ddthHand.*mLeg.*rBody.*rLegMCD.*t11.*t14.*2.0+ddthWaist.*mLeg.*rBody.*rLegMCD.*t10.*t13+ddthWaist.*mLeg.*rBody.*rLegMCD.*t11.*t14+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t10.*t13.*2.0+ddthShoulder.*mLeg.*rBody.*rLegMCD.*t11.*t14.*2.0-dthHand.*dthWaist.*mLeg.*rBody.*rLegMCD.*t10.*t14.*2.0+dthHand.*dthWaist.*mLeg.*rBody.*rLegMCD.*t11.*t13.*2.0-dthWaist.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t10.*t14.*2.0+dthWaist.*dthShoulder.*mLeg.*rBody.*rLegMCD.*t11.*t13.*2.0;
