function dKE = find_dKE(InertiaLeg,InertiaArm,InertiaBody,ddthHand,ddthWaist,ddthShoulder,ddxHand,ddyHand,dthHand,dthWaist,dthShoulder,dxHand,dyHand,g,kPB,mArm,mBody,mLeg,mPB,rArm,rArmMCD,rBody,rBodyMCD,rLegMCD,thHand,thShoulder,thWaist,yHand)
%FIND_DKE
%    DKE = FIND_DKE(T,INERTIALEG,INERTIAARM,INERTIABODY,DDTHHAND,DDTHWAIST,DDTHSHOULDER,DDXHAND,DDYHAND,DTHHAND,DTHWAIST,DTHSHOULDER,DXHAND,DYHAND,G,KPB,MARM,MBODY,MLEG,MPB,RARM,RARMMCD,RBODY,RBODYMCD,RLEGMCD,THHAND,THSHOULDER,THWAIST,YHAND)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 19:55:47

t2 = cos(thHand);
t3 = sin(thHand);
t4 = ddthHand+ddthShoulder;
t5 = dthHand+dthShoulder;
t6 = thHand+thShoulder;
t7 = dthHand.^2;
t13 = -ddyHand;
t14 = -dxHand;
t15 = -dyHand;
t23 = pi./2.0;
t8 = ddthWaist+t4;
t9 = dthWaist+t5;
t10 = cos(t6);
t11 = sin(t6);
t12 = t6+thWaist;
t16 = ddthHand.*rArm.*t2;
t17 = dthHand.*rArm.*t2;
t18 = ddthHand.*rArm.*t3;
t19 = dthHand.*rArm.*t3;
t22 = t5.^2;
t26 = rArm.*t2.*t7;
t27 = rArm.*t3.*t7;
t28 = t23+thHand;
t30 = t6+t23;
t20 = cos(t12);
t21 = sin(t12);
t24 = t9.^2;
t25 = -t16;
t29 = cos(t28);
t31 = cos(t30);
t32 = dthHand.*rArm.*t29;
dKE = mArm.*((dyHand-dthHand.*rArmMCD.*t3).*(t13+ddthHand.*rArmMCD.*t3+rArmMCD.*t2.*t7).*2.0-(dxHand-dthHand.*rArmMCD.*t2).*(ddxHand-ddthHand.*rArmMCD.*t2+rArmMCD.*t3.*t7).*2.0).*(-1.0./2.0)-(mBody.*((t14+t17+rBodyMCD.*t5.*t10).*(ddxHand+t25+t27-rBodyMCD.*t4.*t10+rBodyMCD.*t11.*t22).*2.0-(t15+t19+rBodyMCD.*t5.*t11).*(t13+t18+t26+rBodyMCD.*t4.*t11+rBodyMCD.*t10.*t22).*2.0))./2.0+(mPB.*(ddxHand.*dxHand.*2.0+ddyHand.*dyHand.*2.0))./2.0-(mLeg.*((t14+t17+rBody.*t5.*t10+rLegMCD.*t9.*t20).*(ddxHand+t25+t27-rBody.*t4.*t10+rBody.*t11.*t22-rLegMCD.*t8.*t20+rLegMCD.*t21.*t24).*2.0-(t15+t19+rBody.*t5.*t11+rLegMCD.*t9.*t21).*(t13+t18+t26+rBody.*t4.*t11+rBody.*t10.*t22+rLegMCD.*t8.*t21+rLegMCD.*t20.*t24).*2.0))./2.0+g.*mLeg.*(dyHand+t32+rBody.*t5.*t31+rLegMCD.*t9.*cos(t12+t23))+g.*mBody.*(dyHand+t32+rBodyMCD.*t5.*t31)+InertiaArm.*ddthHand.*dthHand+InertiaLeg.*t8.*t9+InertiaBody.*t4.*t5+dyHand.*g.*mPB+g.*mArm.*(dyHand+dthHand.*rArmMCD.*t29)+dyHand.*kPB.*yHand;
